###
POST http://localhost:9000/api/posts HTTP/1.1
Content-Type: application/json

{
    "user_id": "02",
    "title": "Oferta de trabajo: Ingeniero de Software Senior",
    "content": "Estamos buscando un ingeniero de software senior con experiencia en desarrollo de aplicaciones empresariales. El candidato ideal deberá tener experiencia en Java, Spring Framework y bases de datos SQL. ¡Únete a nuestro equipo y trabaja en proyectos desafiantes!",
    "src_image": "https://ejemplo.com/imagen_oferta_trabajo.png",  
    "comments": [
        "Tengo experiencia en Java y Spring. ¿Cuál es el proceso de selección?",
        "¿Cuál es el rango salarial para este puesto?"
    ],
    "status": true
}

###
GET http://localhost:9000/api/posts HTTP/1.1

###
GET http://localhost:9000/api/posts/654465951cd5a5d435ed6c9c HTTP/1.1

###
PUT http://localhost:9000/api/posts/654465951cd5a5d435ed6c9c HTTP/1.1
Content-Type: application/json

{
    "user_id": "02",
    "title": "Oferta ",
    "content": "Estamos buscando un ingeniero de software senior con experiencia en desarrollo de aplicaciones empresariales. El candidato ideal deberá tener experiencia en Java, Spring Framework y bases de datos SQL. ¡Únete a nuestro equipo y trabaja en proyectos desafiantes!",
    "src_image": "https://ejemplo.com/imagen_oferta_trabajo.png",  
    "comments": [
        "Tengo experiencia en Java y Spring. ¿Cuál es el proceso de selección?",
        "¿Cuál es el rango salarial para este puesto?"
    ],
    "status": true
}

###
DELETE http://localhost:9000/api/posts/6545186104de7610a7bd9bd3 HTTP/1.1